import types
from typing import Callable, Optional
from .context import Context

class Collection:
    def add_collection(self, coll: Collection, name: Optional[str]):...
    def from_module(self, module: types.ModuleType):...
    def add_task(self, Callable[[Context], None]):...
