# このファイルのあるディレクトリで、$brew bundleを打ち込む

# homebrew自体のアップデート
update

# Formulaを更新
upgrade

# 定番コマンド
install wget
install openssl
install subversion
install git

# 定番言語
install python
install node
install mono

# Bashの補完 bash-completion
# http://d.hatena.ne.jp/youhey/20120501/1335855775
install bash-completion

# Docker
install docker
install boot2docker

# Jsonのパース jq
install jq

# 定番ツール
install sqlite

# コマンドラインでクリックを行う
install cliclick

# コマンドラインで画像編集
install imagemagick

# Google App Engine
install google-app-engine

# 不要なファイルの削除
cleanup
