#!/bin/bash
# https://qiita.com/mkiken/items/af5c40ce0d0c6d3530c7

while read local_ref local_sha1 remote_ref remote_sha1
do
if [[ "${remote_ref##refs/heads/}" = "master" \
  || "${remote_ref##refs/heads/}" = "main" \
  || "${remote_ref##refs/heads/}" = "develop" \
  || "${remote_ref##refs/heads/}" = "qa" \
  || "${remote_ref##refs/heads/}" = "canary" ]]; then
  if [[ "${remote_ref##refs/remotes/origin/}" = "74th" ]]; then
    echo "Skipping check for remote branch '74th'"
    continue
  fi

  echo "Warning: push to remote master, main, or develop, continue? [y/N]"

  exec < /dev/tty
  read ANSWER

  case $ANSWER in
    "Y" | "y" | "yes" | "Yes" | "YES" ) echo "OK. push start.";;
    * ) echo "push failed.";exit 1;;
  esac
  exit 0
fi
done
